### ISSUE TITLE
Watch files for changes

### ISSUE THREAD

**Issue by stylemistake** [stylemistake/runner#1]
We need some function that would watch for file changes and run tasks when it detects changes.

Function should be called `runner_watch`.

Possible implementations:
- using digest functions (`sha1`, `sha256`, `md5`, `md5sum`, etc...) and run through all the files with `sleep 1` (not the best way)
- plain bash just by checking update time on files (better)
- use `inotifywait` (requires a dependency `inotify-tools`, can be optional, best method)

**Comment by bserem** [comment]
Is this dropped or has it been implemented?

**Comment by stylemistake** [comment]
I dropped this feature, as it seemed unnecessary, at least in my use cases. For node, we have nodemon, webpack dev server/middleware; auto-reload out of the box for django or literally any php app.

It shouldn't be difficult to implement, tho.

**Comment by bserem** [comment]
Thanks!

**Comment by stylemistake** [comment]
Reopening this feature, because there might be a good use for it considering the current development in the "next" branch.

**Comment by contributorpw** [comment]
I'm using [watchman](https://github.com/facebook/watchman) for re-run runner.

Unfortunately it looks like `runner` runs `watchman` for to run `runner's tasks`.

`watchman` is truly a powerful tool. It works with tens of thousands of files simultaneously at very low capacities.
