### ISSUE TITLE
Use full task names (with prefix) in commands that accept task names.

### ISSUE THREAD

**Issue by stylemistake** [stylemistake/runner#18]
Before:

``` bash
runner_sequence one two
runner_parallel one two
runner_is_task_defined one two
runner_is_task_defined_verbose one two
```

After:

``` bash
runner_sequence task_one task_two
runner_parallel task_one task_two
runner_is_task_defined task_one task_two # this will be an alias to runner_is_defined
runner_is_defined task_{one,two} # use expansion
runner_is_task_defined_verbose task_{one,two}
```

Motivation is that longer names with prefixes can be autocompleted by a text editor.

Some commands will be able to accept both task names and file/directory names, where `task_` prefix will indicate that this is a task and not a file.

Feedback appreciated.

**Comment by mbrodala** [comment]
Personally I'd stick with `--flags` to pass files to commands/functions. What (no matter how likely) I want to process a file which starts with `task_`?

**Comment by stylemistake** [comment]
@mbrodala This can be implicit by default, tho.

**Comment by mbrodala** [comment]
@stylemistake Could you elaborate on that? I'm not sure what you have in mind here.

**Comment by stylemistake** [comment]
I mean, when you type a runner directive without `--flags`, it should try to guess the parameter type.

* If we type `runner_depends task_webpack` and there are both a task and a file with the same name, it assumes this is a task name, because it starts with a `task_`, and tasks have priority.
* If you use flags, i.e. `runner_depends -f/-t task_webpack`. then it knows what this is.

**Comment by mbrodala** [comment]
You are right. This should also be respected by `runner_sequence` and `runner_parallel`, otherwise something like `runner_sequence task_foo -f task_file` would be ambiguous. (Execute `task_foo` with flag `-f` then execute `task_file` or pass `-f task_file` to `task_foo`?)

**Comment by stylemistake** [comment]
I think `runner_sequence` and `runner_parallel` should only accept task names, so there cannot be any ambiguity.

**Comment by stylemistake** [comment]
By the way, `runner_depends` and `runner_provides` are gonna be directives only (not actual functions, but empty functions for declaration purposes).

**Comment by mbrodala** [comment]
@stylemistake I can personally say that I'm planning to put arguments into a `runner_sequence` invocation so I'd like to keep this.

**Comment by stylemistake** [comment]
Closing this because there are no plans to implement this in the near future, and doesn't align with the current vision of the project.
