### ISSUE TITLE
Test and improve Brew installation

### ISSUE THREAD

**Issue by stylemistake** [stylemistake/runner#23]
If someone has mac by hand, test if installation works:

`brew install stylemistake/formulae/runner`

Also, would be great to add bash and coreutils as dependencies for it, so it installs them automatically.

**Comment by felixSchl** [comment]
Works great after installing bash and coreutils

**Comment by stylemistake** [comment]
Amazing. Does it work without bash and coreutils, though? I would close #5 issue as well :)

**Comment by felixSchl** [comment]
No dice:

```
/usr/local/bin/runner: line 20: greadlink: command not found
/usr/local/bin/runner: line 23: greadlink: command not found
/usr/local/bin/runner: line 27: /runner.sh: No such file or directory
/usr/local/bin/runner: line 31: /cli.sh: No such file or directory
```

**Comment by felixSchl** [comment]
Actually checking out this repo and running `./bin/runner` works a treat even without bash 4 and coreutils!

**Comment by stylemistake** [comment]
Updated the brew formula to 0.8. I listed bash and coreutils as recommended dependencies, and they should install automatically.
