### ISSUE TITLE
thoughts on installing as a git bash alias?

### ISSUE THREAD

**Issue by SKalt** [stylemistake/runner#24]
I got the following to work:
```
mkdir my-project && cd my-project
git init
cd .git
wget https://raw.githubusercontent.com/stylemistake/runner/master/src/runner.sh
chmod +x runner.sh
cat <<eof> config
[alias]
   runner = "!f(){ .git/runner.sh $@; }; f"
eof

cd ..
git runner # runs runner.sh!
```
Some issues remain: I haven't figured out how to pass a runnerfile in, and git consumes all `--help` flags. If those issues were resolved, installing as a git alias would be both cli-enabled, local to a project, and independent of the node ecosystem.

**Comment by stylemistake** [comment]
That's a clever idea.

My advice would be to experiment with making a git extension (this way you'll have control of all the flags (allegedly)).

How to do it: Create an executable script `git-runner`, add it to PATH, and Git will pick it up when you use `git runner`.

Maybe there is some trick to make this process local to repo (maybe modifying PATH in some hooks), but i don't know of any.

**Comment by SKalt** [comment]
Good idea.  I'll get to look into this around Wednesday.

**Comment by SKalt** [comment]
After a bit of research, I'm confident there's no way to localize a git extension to a repository without going the `rvm` route and overriding `cd` (see [the accepted answer to "Execute bash scripts on entering a directory"](https://unix.stackexchange.com/a/21364/234355) for how). I'm unwilling to make that dangerous of a change or deal with possible collision with other tools (e.g. `rvm`).  

So long as you're willing to sacrifice the `--help` flag, I've found 
```
# .git/config
[alias]
  runner = "!f(){ path/to/runner/bin/runner $@; }; f"
```
will detect root-level `runnerfile`s and accept arguments.  Note git does not consume `-h`, so `usage` can still be accessed that way.

**Comment by stylemistake** [comment]
Yes, please do.
