### ISSUE TITLE
Feature request: ability to use `stdin` as a runnerfile

### ISSUE THREAD

**Issue by SKalt** [stylemistake/runner#29]
Many bash scripts are kept in JSON-like formats these days: `package.json#scripts`, `bitbucket_pipelines.yml`, or `travis.yml` are some I have encountered. I'd like to be able to write a program in another language that extracts bash tasks from other, non-bash files, and use the parsed tasks. 

Example node script to create a runnerfile-like string from package.json#scripts:
```javascript
Object.entries(require('package.json').scripts || {})
  .map(([name, script]) => `task_${name}(){ ${script.replace(/;$/, '')}; };`)
  .join('\n')
```

**Comment by stylemistake** [comment]
Made a change which allows using named pipes as runnerfiles.

Now you can do this:

```
bin/runner -f <(cat runnerfile.sh)
```

And if you want to pipe it in, you can do this:

```
cat runnerfile.sh | bin/runner -f -
```

Which in turn is an alias for:

```
cat runnerfile.sh | bin/runner -f /dev/stdin
```

Hope this helps!

**Comment by SKalt** [comment]
This is great! I'm going to mark this closed.  The next steps would be writing scripts to ingest `travis.yml` and `package.json#scripts`, which may or may not fall within the scope of this project.

**Comment by stylemistake** [comment]
@SKalt increasing scope to something more "universal" would be nice.

**Comment by SKalt** [comment]
Glad you say that! I originally found this project since I was looking for a base on which to build a more universal task runner. Think `yarn run`, but without the dependence on node.js. <details><summary>Here's my original spec in case you're interested</summary>
Using a git alias or git extension would allow accessing bash the same way on *nix and within git-managed projects on Windows.

```bash
git run [...runner-opts] [$1: task-name] [...task-params]
git run --seq | --sequence [task-1] [task-2] [...] 
            ^ --all would be a good alternative flag
# advanced functionality similar to CI pipeline tools
# not needed for an MVP
git run --parallel task-1 task-2 ...
git run --sequence task-1 --parallel task-2 task-3 --sequence task-4
```

</details>
