### ISSUE TITLE
python install -- where should new install methods go?

### ISSUE THREAD

**Issue by SKalt** [stylemistake/runner#30]
I'm about to submit a PR for installation via python's `pip`.  Larger question: how should the different installation methods be organized?

**Comment by stylemistake** [comment]
I thought about making it like this: `platform/<platform>/<files>`, where all platform specific files will be isolated, e.g. `platform/npm/package.json`, or `distrib/archlinux/PKGBUILD`.

Not sure how to name that folder, possible variants: `distrib`, `platform`, `packaging`.

**Comment by stylemistake** [comment]
@SKalt 

- git submodules - definitely no
- symlinks - not sure how this would work (package managers will package symlinks and not actual files)

It's safer to just copy files to those dirs, and run a packaging command within that dir. All of this can be automated from the runnerfile.
