### ISSUE TITLE
Return code successful on task failure

### ISSUE THREAD

**Issue by mbrodala** [stylemistake/runner#35]
Given the following `Runnerfile.sh`:

```bash
task_test() {
  return 1
}
```

When running this task I see this output:

```
$ runner test
[01:25:19.119] Starting 'test'...
[01:25:19.127] Task 'test' failed after 2 ms (1)
$ echo $?
0
```

The overall return code indicates success, any idea what's wrong here? Could this be related to #32?

**Comment by mbrodala** [comment]
OK, apparently this goes deeper. If I drop the task again and retry I get this:

```
$ runner test
[01:28:41.317] Task 'test' is not defined!
$ echo $?
0
```

But again, the status code indicates success ...

**Comment by mbrodala** [comment]
And one more finding: the return code apparently works fine for the implicit `default` task.

Given this `Runnerfile.sh`:

```bash
task_default() {
  false
}
```

The behavior is as expected:

```
$ runner
[01:34:28.467] Starting 'default'...
[01:34:28.479] Task 'default' failed after 2 ms (1)
$ echo $?
1
```

However, explicitly invoking that task shows the wrong behavior again:

```
$ runner default
[01:35:13.271] Starting 'default'...
[01:35:13.279] Task 'default' failed after 1 ms (1)
$ echo $?
0
```

**Comment by mbrodala** [comment]
After a little debugging I found that `runner_sequence()` swallows the actual task return code. A small fix could be this:

```diff
-    runner_run_task "${task}" || return
+    runner_run_task "${task}" || return $?
```

Could it be that a plain `|| return` is a bad idea?

**Comment by stylemistake** [comment]
I had that issue with plain returns, and i thought most of them were fixed. It is supposed to implicitly return the last exit code, but with such bugs popping up I am no longer sure.

Good catch.

**Comment by mbrodala** [comment]
@stylemistake Any updates on this? We had to gradually drop the Task Runner in all of our builds due to this ...

**Comment by stylemistake** [comment]
@mbrodala I have pushed a fix, along with a test for your case. Check if it works for you, and if you need a new release on npm, let me know.

**Comment by mbrodala** [comment]
I wasn't 100% sure that my fix was _the_ fix but evidently it works now, thanks. :-)
