### ISSUE TITLE
Compatibility with bash v3

### ISSUE THREAD

**Issue by stylemistake** [stylemistake/runner#5]
Git for Windows was shipping with old `bash` and `coreutils` a while ago, but the newer versions released recently are up to date and are recommended releases to use. Therefore, no need to support issues with old Git Bash.

Bash v3 is still a default version pre-installed on OS X, and that is problematic.

The only bash-specific thing causing us problems is the `runner_color` associative array, which can be refactored to a function, but using a function for this results in a good amount of overhead (about ~5ms per task).

Other non-bash issues: #4

**Comment by Spaxe** [comment]
Another bash v3 issue: `declare` doesn't have a `-g` flag in bashv3, but it does in bashv4.

**Comment by stylemistake** [comment]
I think I've finally resolved this issue in a relatively painless way. The only thing that does not work is the color (`runner_colorize` is replaced with an empty function for bash version 3).

*This needs testing on an actual macOS.*

**Comment by felixSchl** [comment]
I wouldn't call 5ms a good amount of overhead in bash land ;-)

You could always keep both implementations around and source them based on OS.

Here's what I get running it on bash v3 on OSX:

```
/usr/local/Cellar/runner/0.7.1/src/runner.sh: line 12: declare: -g: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
/usr/local/Cellar/runner/0.7.1/src/runner.sh: line 23: declare: -g: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
/usr/local/Cellar/runner/0.7.1/src/runner.sh: line 29: declare: -g: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
/usr/local/Cellar/runner/0.7.1/src/runner.sh: line 30: declare: -g: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
/usr/local/Cellar/runner/0.7.1/src/runner.sh: line 93: declare: -g: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
/usr/local/Cellar/runner/0.7.1/src/cli.sh: line 6: declare: -g: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
/usr/local/Cellar/runner/0.7.1/src/cli.sh: line 9: declare: -g: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
/usr/local/Cellar/runner/0.7.1/src/cli.sh: line 17: declare: -g: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
/usr/local/Cellar/runner/0.7.1/src/cli.sh: line 18: declare: -g: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
/usr/local/Cellar/runner/0.7.1/src/cli.sh: line 19: declare: -g: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
[\e[0m12:08:08.192\e[0m] Available tasks:
[\e[0m12:08:08.200\e[0m]   \e[0m<none>\e[0m
```

**Comment by felixSchl** [comment]
Sorry, those errors **do not** occur when I run from a git checkout, just from homebrew

**Comment by stylemistake** [comment]
Can you try Git version instead? Run `test/test.sh` to see if it works.

**Comment by SKalt** [comment]
Hi, [the readme dependency section](https://github.com/stylemistake/runner#dependencies) still lists bash >= 4 as a requirement.  With this issue closed, is this still correct?

**Comment by stylemistake** [comment]
@SKalt I would call it a soft dependency, because that's the bash version it was designed for, but yeah, it works just fine with bash v3 (with some features disabled).
